name: Feature Request
description: Suggest an idea for this project
title: "[enhancement]: "
labels: [enhancement]
body:
  - type: markdown
    attributes:
      value: |
        Please double check the [Common Issues](https://github.com/samemory/homebridge-eufy-security/wiki/Common-Issues) before submitting a request.
  - type: textarea
    id: feature-request
    attributes:
      label: Describe the solution you'd like
      description: A clear and concise description of what you want to happen.
      placeholder: Tell us what you want!
    validations:
      required: true
