name: Release

on:
  push:
    branches: [ master ]
  workflow_dispatch:
    inputs:
      tag:
        description: 'tag: latest/rc/beta'
        required: true
        default: 'latest'
      preid:
        description: 'preid: rc/beta'
        required: false
        default: ''
      branch:
        description: 'branch: master/next/beta'
        required: true
        default: 'master'

jobs:

  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [22]
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.branch }}
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - run: npm install
      - run: npm ci
      - run: npm run lint
      - run: npm run build
  # version:
  #   runs-on: ubuntu-latest
  #   strategy:
  #     matrix:
  #       node-version: [24]
  #   needs: build
  #   steps:
  #     - uses: actions/checkout@v4
  #       with:
  #         ref: ${{ github.event.inputs.branch }}
  #         token: ${{ secrets.GITHUB_TOKEN }}

  #     - name: Version Check
  #       uses: thebongy/version-check@v2
  #       with:
  #         file: ./package.json
  #         tagFormat: v${version}
  #         failBuild: true
  #       id: version_check
  #     - name: Push the change
  #       uses: actions/checkout@v4
  #       with:
  #         ref: ${{ github.event.inputs.branch }}
  #         # token: ${{ secrets.BUILD_SVC_PAT }}
  #         token: ${{ secrets.GITHUB_TOKEN }}
  #     - run: git config --global user.name '[GitHub Bot]'
  #     - run: git config --global user.email '<>'
  #     - run: npm version ${{ steps.version_check.outputs.rawVersion }} --preid=${{ github.event.inputs.preid }} -m "[${{ github.event.inputs.tag }}] %s"
  #     - run: npm update homebridge-eufy-security-e30
  #     - run: git push --force
  #     - run: git push origin --tags --force

  publish:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.branch }}
      - name: Version Check
        uses: thebongy/version-check@v2
        with:
          file: ./package.json
          tagFormat: v${version}
          failBuild: true
      - uses: actions/setup-node@v4
        with:
          node-version: 22
          registry-url: https://registry.npmjs.org/
      - run: npm i
      - run: npm publish --access public --tag latest
        env:
          NODE_AUTH_TOKEN: ${{secrets.npm_token}}
